### ISSUE TITLE
Could you please provide the Canny Control dateset?

### ISSUE THREAD

**Issue by JoongLeo** [mvrl/GeoSynth#10]

**Comment by Vishu26** [comment]
Hi

You can just run the canny algorithm in the `opencv` package on the satellite images to create the dataset.

Thanks

**Comment by jacobsn** [comment]
With default parameters?

**Comment by Vishu26** [comment]
All default parameters except the 1st threshold set to 100 and the 2nd threshold set to 200.

**Comment by jacobsn** [comment]
Probably worth throwing a script in to do that so people can replicate results.

**Comment by yinliaoabc** [comment]
Could you please provide the Canny dateset?The effect I generated myself is not good.Thanks!

**Comment by Vishu26** [comment]
Below I'm sharing a script to load the Canny dataset. After reading the satellite image, I run the canny detector algorithm defined in the ControlNet repo (which uses `opencv`):

```python
import json
import cv2
import numpy as np
from ..ControlNet.annotator.canny import CannyDetector
from ..ControlNet.annotator.util import HWC3
from torch.utils.data import Dataset


class Dataset(Dataset):
    def __init__(self, prompt_path):
        self.data = json.load(open(prompt_path, "rt"))
        self.apply_canny = CannyDetector()

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]

        target_filename = item["target"]
        prompt = item["prompt"]

        target = cv2.imread("../" + target_filename)

        # Do not forget that OpenCV read images in BGR order.
        target = cv2.cvtColor(target, cv2.COLOR_BGR2RGB)

        # Apply Canny Edge Algorithm
        source = self.apply_canny(target, 100, 200)
        source = HWC3(source)

        # Normalize source images to [0, 1].
        source = source.astype(np.float32) / 255.0

        # Normalize target images to [-1, 1].
        target = (target.astype(np.float32) / 127.5) - 1.0

        return dict(
            jpg=target, txt=prompt, hint=source
        )
```

**Comment by JoongLeo** [comment]
> Below I'm sharing a script to load the Canny dataset. After reading the satellite image, I run the canny detector algorithm defined in the ControlNet repo (which uses `opencv`):
> 
> ```python
> import json
> import cv2
> import numpy as np
> from ..ControlNet.annotator.canny import CannyDetector
> from ..ControlNet.annotator.util import HWC3
> from torch.utils.data import Dataset
> 
> 
> class Dataset(Dataset):
>     def __init__(self, prompt_path):
>         self.data = json.load(open(prompt_path, "rt"))
>         self.apply_canny = CannyDetector()
> 
>     def __len__(self):
>         return len(self.data)
> 
>     def __getitem__(self, idx):
>         item = self.data[idx]
> 
>         target_filename = item["target"]
>         prompt = item["prompt"]
> 
>         target = cv2.imread("../" + target_filename)
> 
>         # Do not forget that OpenCV read images in BGR order.
>         target = cv2.cvtColor(target, cv2.COLOR_BGR2RGB)
> 
>         # Apply Canny Edge Algorithm
>         source = self.apply_canny(target, 100, 200)
>         source = HWC3(source)
> 
>         # Normalize source images to [0, 1].
>         source = source.astype(np.float32) / 255.0
> 
>         # Normalize target images to [-1, 1].
>         target = (target.astype(np.float32) / 127.5) - 1.0
> 
>         return dict(
>             jpg=target, txt=prompt, hint=source
>         )
> ```

Thanks for the code, I will try it out and thanks again for this great work.
