### ISSUE TITLE
How to download the OSM data?

### ISSUE THREAD

**Issue by xuliu-cyber** [mvrl/GeoSynth#3]
Hello, thanks for your excellent work! Could you share how to download the OSM data and its corresponding RS image？

**Comment by Vishu26** [comment]
We will release instructions on how to download data after the conference.

**Comment by miquel-espinosa** [comment]
> Hello, thanks for your excellent work! Could you share how to download the OSM data and its corresponding RS image？

Check this out, it might be useful.
https://github.com/miquel-espinosa/map-sat

**Comment by Vishu26** [comment]
The dataset is released. Information is present in the README.
