### ISSUE TITLE
Request for control_sd21_ini.ckpt File in train.py Script

### ISSUE THREAD

**Issue by mj-x** [mvrl/GeoSynth#5]
Hi,
I hope you're doing well. I’ve been exploring your project and noticed the following line in the GeoSynth/scripts/train.py file:

resume_path = "GeoSynth/scripts/control_sd21_ini.ckpt"

I was wondering if you could provide the control_sd21_ini.ckpt file or point me in the right direction to obtain it? It seems necessary for running the script, and I would love to test it on my end.

Thank you in advance for your help, and I appreciate your amazing work on this project!

**Comment by Vishu26** [comment]
Hello,

You can use the `tool_add_control_sd21.py` script in the repository to add control to sd 2.1 and get the `control_sd21_ini.ckpt`. The script is present here: `GeoSynth/ControlNet/tool_add_control_sd21.py`.

You first have to download the sd 2.1 checkpoint from: https://huggingface.co/stabilityai/stable-diffusion-2-1-base/blob/main/v2-1_512-ema-pruned.ckpt. Then just call the script like:

`python tool_add_control_sd21.py ./models/v2-1_512-ema-pruned.ckpt ./models/control_sd21_ini.ckpt`

Thank you!

**Comment by mj-x** [comment]
Hi，
Thank you so much for your detailed instructions! I really appreciate you taking the time to guide me through the process. I’ll follow your steps and try running the script with the SD 2.1 checkpoint.Thanks again for your amazing work!

**Comment by mj-x** [comment]
Hi ,

I hope you're doing great! I've been making good progress, but I have another quick question regarding the `get_satclip_embeds.py` script.

I noticed this line in the code:

```python
df = pd.read_csv("input_data_list.csv")
```

It seems that the `input_data_list.csv` file is missing from the repository. Could you kindly let me know where I can find it or provide some guidance on how to generate this file?

Thank you once again for your continued support, and I truly appreciate all your work on this amazing project!

Best regards！
