### ISSUE TITLE
Request for `input_data_list.csv` file in `get_satclip_embeds.py` script

### ISSUE THREAD

**Issue by mj-x** [mvrl/GeoSynth#6]
Hi ,

I hope you're doing great! I've been making good progress, but I have another quick question regarding the `get_satclip_embeds.py` script.

I noticed this line in the code:

```python
df = pd.read_csv("input_data_list.csv")
```

It seems that the `input_data_list.csv` file is missing from the repository. Could you kindly let me know where I can find it or provide some guidance on how to generate this file?

Thank you once again for your continued support, and I truly appreciate all your work on this amazing project!

Best regards！

**Comment by Vishu26** [comment]
Hello

Thank you for raising the issue. The file was generated by randomly sampling locations across 10 cities in the USA. We have now uploaded the `input_data_list.csv` to [Box](https://wustl.box.com/s/lxuopink74nf32u869v7ea42jlh6jkck). 

Thank you!

**Comment by mj-x** [comment]
Hi,

Thank you so much for your quick response and for providing the input_data_list.csv file on Box! I really appreciate your help and the effort you put into maintaining this fantastic project. 

Thanks again for your support!
