### ISSUE TITLE
AssertionError when Generating Images Using Custom Trained GeoSynth Model (geosynth/model_geosynth.ckpt) in Stable Diffusion ControlNet Pipeline

### ISSUE THREAD

**Issue by mj-x** [mvrl/GeoSynth#7]
Hi，
I hope this message finds you well.  I would like to express my gratitude for your work and the support you've provided so far. I have raised questions about using a custom trained GeoSynth model for image generation before, and while I appreciate the previous guidance, I am still facing some difficulties that I was unable to resolve.

I have successfully trained the GeoSynth model using the provided train.py script and have obtained a ckpt file located in the geosynth folder **(geosynth/model_geosynth.ckpt).** However, when I attempt to use this trained model within the StableDiffusionControlNetPipeline for generating images, I continue to encounter errors.

Approach:
Model Loading: I am using the create_model and load_state_dict functions to load the trained ckpt file. The configuration file I used is **cldm_v21.yaml (config_path)**, and the model checkpoint is **geosynth/model_geosynth.ckpt (ckpt_path)**.
Pipeline Integration: After loading the custom ControlNet model, I pass it to the StableDiffusionControlNetPipeline for image generation.
Input and Output: I provide a prompt and an input image (e.g., a satellite image), but I receive an error when trying to generate and save the output image.
**Here is the test code I used:**

```
# Load ControlNet model
controlnet = create_model(config_path).to('cuda')
controlnet.load_state_dict(load_state_dict(ckpt_path, location="cuda"))

# Load StableDiffusionControlNetPipeline
pipe = StableDiffusionControlNetPipeline.from_pretrained(
    "stabilityai/stable-diffusion-2-1-base",
    controlnet=controlnet
)
pipe = pipe.to("cuda")

# Image processing and generation
img = Image.open(image_path).convert("RGB")
img_tensor = transforms.ToTensor()(img).unsqueeze(0).to("cuda")

generator = torch.manual_seed(10345340)
generated_image = pipe(prompt="A satellite image with a city layout", image=img_tensor, generator=generator).images[0]
generated_image.save("generated_city.jpg")
```

**Error Traceback:**
`Traceback (most recent call last):
  File "D:/GeoSynth-main/scripts/test.py", line 59, in <module> 
    image = pipe(
  File "D:\APP\Conda\envs\geosynth\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\APP\Conda\envs\geosynth\lib\site-packages\diffusers\pipelines\controlnet\pipeline_controlnet.py", line 1075, in __call__
    self.check_inputs(
  File "D:\APP\Conda\envs\geosynth\lib\site-packages\diffusers\pipelines\controlnet\pipeline_controlnet.py", line 680, in check_inputs
    assert False
AssertionError

Process finished with exit code 1
`

**Issues Encountered:**
The error (AssertionError) occurs during the check_inputs function in the pipeline, suggesting that one of the inputs is not valid or in the expected format.
Despite the guidance provided earlier, I suspect that there might still be an issue with how the custom ControlNet model (from geosynth/model_geosynth.ckpt) is loaded or passed to the StableDiffusionControlNetPipeline.
The image generation process fails, and no output image is saved.

**Could you kindly provide further guidance on:**

The correct way to load and use a custom ControlNet model (ckpt) within the StableDiffusionControlNetPipeline.
Any adjustments or changes needed in the input image processing or pipeline configuration.
Potential reasons why the pipeline fails and how to resolve the AssertionError.
I sincerely apologize for reaching out again and taking more of your time, but your help would be invaluable in resolving this issue. Thank you for your continued support and understanding.

**Comment by Vishu26** [comment]
Hello 

You first have to convert your trained model (`geosynth/model_geosynth.ckpt`) to `ControlNetModel` format in `diffusers`. This can be done by a script present in the diffusers repository: `scripts/convert_original_controlnet_to_diffusers.py`. 

I have also created a bash script to convert the ckpt file to `ControlNetModel` format, which is present here: https://github.com/mvrl/GeoSynth/blob/main/scripts/tool_convert_to_diffusers.sh. First clone the `diffusers` repository. Then run the script as below:

```bash
./tool_convert_to_diffusers.sh path/to/diffusers/repository path/to/checkpoint path/to/cldm_v21.yaml ./models/
```

This will create `safetensors` and `config.json` files in the `./models/` path. Then you can load the model in `StableDiffusionControlNetPipeline`:

```python
from diffusers import StableDiffusionControlNetPipeline, ControlNetModel

controlnet = ControlNetModel.from_single_file("./models/diffusion_pytorch_model.safetensors", config="./models/config.json")
pipe = StableDiffusionControlNetPipeline.from_pretrained("stabilityai/stable-diffusion-2-1-base", controlnet=controlnet)
```

Good Luck!

**Comment by mj-x** [comment]
Hi,
Thank you so much for your detailed response and the helpful instructions!I appreciate your help and will follow the steps to convert the model and try it out in the pipeline.
Your support is invaluable, and I look forward to seeing the results. .Thanks again for your help!

Best regards.
