### ISSUE TITLE
"Missing load Module and get_satclip Function in get_satclip_embeds.py"

### ISSUE THREAD

**Issue by JoongLeo** [mvrl/GeoSynth#8]
Hello! Thank you for your work on this project. I noticed an issue in the **get_satclip_embeds.py** file, where the line **from load import get_satclip** results in an import error. It seems the load module and the **get_satclip** function are **missing** from the repository. Could you please provide them or guide me on how to resolve this?

Thanks in advance for your help!

**Comment by Vishu26** [comment]
Thank you for raising the issue. You will have to clone the [satclip](https://github.com/microsoft/satclip) repository locally. It has a file load.py using which you can load the satclip location encoder.

Best of luck!

**Comment by JoongLeo** [comment]
Thank you！
