### ISSUE TITLE
Broken URLs: mapbox style + dataset URL

### ISSUE THREAD

**Issue by philadias** [mvrl/GeoSynth#9]
Hi all,

Following URLs are broken, could you please fix it? I'm particularly interested in the style file. -- thanks!

> The style file can be downloaded from [here](https://wustl.box.com/s/087sja3r137jotfbmy99svcysaamhsir). The dataset can be downloaded from [here](https://wustl.box.com/s/lxuopink74nf32u869v7ea42jlh6jkck).

**Comment by Vishu26** [comment]
Hi @philadias 

I have updated the new link: [here](https://wustl.box.com/s/epgjl8v4myaeo3q64sh1tn3cea5w5vke). Sorry for the confusion, Box disables the link after a stipulated date. I have increased that date for now.

Thanks!

**Comment by philadias** [comment]
Wonderful, that works now.

Thanks for the prompt reply and the very nice work/repo!
